MODEL:
  name: BAAI/bge-m3
  reranker: BAAI/bge-reranker-v2-m3
DS:
  dir: data/cultural_objects_mnn.csv
DB:
  user: postgres
  password: "12345"
  host: "127.0.0.1"
  port: "5432"
  database: "gorkycode"
BGE:
  colbert: 1
  dense: 1
  sparse: 0.3
GEO:
  avg_speed: 4.5
RELEVANCE:
  weight_reranker: 0.8
  weight_distance: 1
