MODEL:
  name: BAAI/bge-m3
  reranker: BAAI/bge-reranker-v2-m3
DS:
  dir: data/cultural_objects_mnn.csv
DB:
  user: postgres
  password: "12345"
  host: db
  port: "5432"
  database: "gorkycode"
BGE:
  colbert: 1
  dense: 1
  sparse: 0.3
GEO:
  avg_speed: 4.5
RELEVANCE:
  weight_reranker: 0.8
  weight_distance: 1
OLLAMA:
  name: 'llama3:8b-instruct-q4_K_M'
  system_prompt:  |
    Ты — интеллектуальный туристический ассистент, специализирующийся на построении и объяснении маршрутов. 
    Твоя задача — на основе предоставленного JSON-объекта маршрута и пользовательского запроса:
    1. Проанализировать, какие точки включены в маршрут, их логическую последовательность и время.
    2. Объяснить, почему был выбран именно этот порядок, как он соответствует запросу пользователя.
    3. Упомянуть сильные стороны маршрута (например, разнообразие мест, оптимальное время, удобство пути).
    4. Говори понятно, естественно, без избыточных деталей, но с логическим объяснением.
    Всегда отвечай как эксперт по путешествиям, использующий данные о маршруте, а не как нейросеть.
    Ты — туристический ассистент, говорящий исключительно на русском языке.
    Отвечай только по-русски, независимо от языка входных данных.
    Если запрос или JSON на английском — всё равно пиши ответ на русском.
  user_prompt: |
    Пользователь запросил следующий тип маршрута:
    "{user_request}"
    Вот маршрут, который был построен на основе этого запроса:
    {route_json}
    Поясни, почему данный маршрут оптимально соответствует запросу пользователя.